### ISSUE TITLE
Cannot run npm test

### ISSUE THREAD

**Issue by zaaack** [ts-llvm/ts-llvm#3]
When I run `npm test`, I got an error:

```ts
Error: Command failed: llc -O3 -filetype=obj array.bc -o array.o
llc: array.bc: error: Invalid type for value

    at checkExecSyncError (child_process.js:600:11)
    at Object.execFileSync (child_process.js:618:13)
    at writeExecutableToFile (/Users/z/Projects/Node/ts-llvm/src/main.ts:106:5)
    at main (/Users/z/Projects/Node/ts-llvm/src/main.ts:72:5)
    at Object.<anonymous> (/Users/z/Projects/Node/ts-llvm/src/main.ts:22:3)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Module.m._compile (/Users/z/Projects/Node/ts-llvm/node_modules/ts-node/src/index.ts:439:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/Users/z/Projects/Node/ts-llvm/node_modules/ts-node/src/index.ts:442:12)
    at Module.load (internal/modules/cjs/loader.js:599:32)

```
or

```
$ npm test

> ts-llvm@0.0.0 test /Users/z/Projects/Node/ts-llvm
> ts-node test/test-runner.ts

Error: Command failed: llc -O3 -filetype=obj boolean.bc -o boolean.o
llc: boolean.bc: error: Invalid type for value

    at checkExecSyncError (child_process.js:600:11)
    at Object.execFileSync (child_process.js:618:13)
    at writeExecutableToFile (/Users/z/Projects/Node/ts-llvm/src/main.ts:106:5)
    at main (/Users/z/Projects/Node/ts-llvm/src/main.ts:72:5)
    at Object.<anonymous> (/Users/z/Projects/Node/ts-llvm/src/main.ts:22:3)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Module.m._compile (/Users/z/Projects/Node/ts-llvm/node_modules/ts-node/src/index.ts:439:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/Users/z/Projects/Node/ts-llvm/node_modules/ts-node/src/index.ts:442:12)
    at Module.load (internal/modules/cjs/loader.js:599:32)
```
I tried with llvm@7.0.0 and llvm@4.0.1 (macos, installed via brew), the npm install finished without any error message,  did I miss something?

**Comment by zaaack** [comment]
Sorry, I think I figured it out, with this steps finally the tests passed.

```sh
brew install --with-clang llvm

echo 'export PATH="/usr/local/opt/llvm/bin:$PATH"' >> ~/.zshrc
echo 'LDFLAGS="-L/usr/local/opt/llvm/lib"' >> ~/.zshrc
echo 'CPPFLAGS="-I/usr/local/opt/llvm/include"' >> ~/.zshrc

```

@Kingwl
